//
//  DeveloperPreview.swift
//  AirbnbClone
//
//  Created by Karthik Rashinkar on 23/04/24.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
              numberOfBeadroom: 4,
              numberOfBathroom: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4",],
              address: "123 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
              numberOfBeadroom: 4,
              numberOfBathroom: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["listing-2", "listing-3", "listing-4", "listing-1",],
              address: "123 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
              numberOfBeadroom: 4,
              numberOfBathroom: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["listing-3", "listing-4", "listing-5", "listing-6",],
              address: "123 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
              numberOfBeadroom: 4,
              numberOfBathroom: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["listing-4", "listing-5", "listing-6", "listing-7",],
              address: "123 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
              numberOfBeadroom: 4,
              numberOfBathroom: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["listing-5", "listing-6", "listing-7", "listing-8",],
              address: "123 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
              numberOfBeadroom: 4,
              numberOfBathroom: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["listing-6", "listing-7", "listing-8", "listing-1",],
              address: "123 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
                  numberOfBeadroom: 4,
                  numberOfBathroom: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  imageURLs: ["listing-7", "listing-8", "listing-1", "listing-2",],
                  address: "123 Main St",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.86,
                  features: [.selfCheckin, .superHost],
                  amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
                  type: .villa
                 ),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerImageUrl: "male-profile-photo", ownerName: "Aditya Roy Kapoor",
                  numberOfBeadroom: 4,
                  numberOfBathroom: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  imageURLs: ["listing-8", "listing-1", "listing-2", "listing-3",],
                  address: "123 Main St",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.86,
                  features: [.selfCheckin, .superHost],
                  amenities: [.wifi,.alarmSystem, .balcony, .laundry, .tv],
                  type: .villa
                 ),
    ]
}
